# Generated by Django 2.1.3 on 2018-12-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_present', models.BooleanField(default=True)),
                ('white_present', models.BooleanField(default=True)),
                ('board_state', models.CharField(default='', max_length=64)),
                ('game_state', models.CharField(choices=[('in-progress', (('TW', "White's turn"), ('TB', "Black's turn"))), ('ended', (('EW', 'White won'), ('EB', 'Black won'), ('ED', 'Draw')))], default='TW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_black_set', to='chess.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_white_set', to='chess.User'),
        ),
    ]
